### Check User 1 Balance (Initial)
# Should be 500,000 (or less if previous tests ran)
GET http://localhost:8080/clients/1

###

### First Subscription (Success)
# User 1 subscribes to Fund 2 (125,000)
# Should succeed
POST http://localhost:8080/funds/subscribe
Content-Type: application/json

{
  "clientId": "1",
  "fundId": "2"
}

###

### Second Subscription (Idempotency Check - Fail)
# User 1 tries to subscribe to Fund 2 AGAIN
# Should fail with 400 Bad Request and message "Client is already subscribed to fund FPV_ECOPETROL"
POST http://localhost:8080/funds/subscribe
Content-Type: application/json

{
  "clientId": "1",
  "fundId": "2"
}

###

### Check User 1 Balance
# Should be deducted only once (500,000 - 125,000 = 375,000)
GET http://localhost:8080/clients/1

###

### Check Transaction History
# Should show only one OPENING transaction for Fund 2
GET http://localhost:8080/transactions/history/1
