### Check User 2 Balance (Initial)
# Should be 100,000 (unless previous test modified it)
GET http://localhost:8080/clients/2

###

### Subscribe to Fund 1 (SMS Notification Case)
# User 2 (100,000) subscribes to Fund 1 (75,000)
# Should succeed. User 2 has NotificationPreference: SMS
# The backend should log/process the SMS notification
POST http://localhost:8080/funds/subscribe
Content-Type: application/json

{
  "clientId": "2",
  "fundId": "1"
}

###

### Check User 2 Balance (After Subscription)
# Should be 25,000 (100,000 - 75,000)
GET http://localhost:8080/clients/2

###

### Check Transaction History
# Should show the subscription transaction
GET http://localhost:8080/transactions/history/2
